### ISSUE TITLE
Video not playing after finishing other one

### ISSUE THREAD

**Issue by HerXayah** [ozencb/couchtube#6] opened 2024-11-12 22:50 UTC
Whenever i play a Video in the app and it finishes, it wont play the next video and i need to either press Off and On to get it to load or i need to switch channel and switch back for it to play the next video.
Otherwise it will be stuck in this:
![image](https://github.com/user-attachments/assets/046f7cc0-3b2d-47e1-96a4-63a54d4ac38e)

Here is my videos.json file i use:
https://gist.github.com/HerXayah/3366fbfdd6448157fe52b091a32b0635

**Comment by codenamek83** [comment] 2024-11-13 00:40
Hi @HerXayah 

I'm not the developer, but I've been testing this application for the last 2 days and had similar issues. Is your CouchTube instance behind a reverse proxy server, and are you accessing it via a domain name? YouTube has some restrictions or policies on how content can be watched outside of their platform. I ran into similar issues when I was initially testing the app with a private IP address. But once I put it behind a reverse proxy, everything worked fine. I checked some of the videos in your playlist, and you have about 694 videos across 2 channels. I'd recommend trying a few videos and channels first to see if it works smoothly.

**Comment by HerXayah** [comment] 2024-11-13 00:44
Using it via Unraid atm behind a locsl IP only. 
No RP.
The Speedrun Category has the same problem and way fewer Videos

**Comment by codenamek83** [comment] 2024-11-13 01:00
The instance I'm testing is behind a reverse proxy with a subdomain. I have around 200 videos across 4 channels. For testing, each channel has different types of videos like music, movies, and documentaries. The videos switch flawlessly, but my issue is that the next video keeps cycling through the 4 channels in a round-robin fashion. I'm not sure if this is the intended design, but I plan to open another request about it. Still, I’d recommend trying it with a smaller playlist with just a few channels and videos to help isolate the problem.

**Comment by ozencb** [comment] 2024-11-15 17:19
Hello, thanks for the feedback!

This is caused by `sectionEnd` times being higher than the real length of the video. I now added an extra check to to see if the video has ended, that should fix it.

I am going to close the issue, please reopen if you encounter it again

**Comment by ozencb** [comment] 2024-11-15 17:19
Hello, thanks for the feedback!

This is caused by `sectionEnd` times being higher than the real length of the video. I now added an extra check to to see if the video has ended, that should fix it.

I am going to close the issue, please reopen if you encounter it again

**Closed as completed by ozencb** 2024-11-15 17:19 UTC
